project_name: ghreport
env:
  - GO111MODULE=on
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64

archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip

nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/Jmainguy/ghreport
  description: Check Github for Pull Requests, that are not Drafts, in repos the user cares about.
  maintainer: Jonathan Seth Mainguy <jon@soh.re>
  license: GPLv2
  vendor: Jmainguy
  release: 1
  replacements:
    amd64: x86_64
  overrides:
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{.Release}}.{{ .Arch }}"
  formats:
  - deb
  - rpm

brews:
  - tap:
      owner: jmainguy
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/Jmainguy/ghreport
    description: "Check Github for Pull Requests, that are not Drafts, in repos the user cares about."
    license: "GPL-2.0"
    commit_author:
      name: Jonathan Mainguy
      email: jon@soh.re
    test: |
      system "#{bin}/ghreport"
    install: |
      bin.install "ghreport"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
