on:
    push:

name: push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get Build Tools
        run: |
          go install github.com/ory/go-acc@latest

      - name: git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install dependencies
        run: |
          go mod download

      - name: Run Unit tests
        run: |
          go-acc .

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt

  build:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: install lint
        run: GO111MODULE=off go get golang.org/x/lint/golint

      - name: run golint and go fmt
        run: ./tests/fmtlint.sh

      - name: go build
        run: go build
