on:
    push:

name: push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.3'

      - name: Get Build Tools
        run: |
          GO111MODULE=on go get github.com/ory/go-acc

      - name: Add $GOPATH/bin to $PATH
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: git checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go mod download

      - name: Run Unit tests
        run: |
          go-acc .

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt

  build:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'

      - name: git checkout
        uses: actions/checkout@v2

      - name: install lint
        run: GO111MODULE=off go get golang.org/x/lint/golint

      - name: run golint and go fmt
        run: ./tests/fmtlint.sh

      - name: go build
        run: go build
